### ISSUE TITLE
Does it work with anki 2.1.45?

### ISSUE THREAD

**Issue by gustavosmendes** [RisingOrange/anki-enhanced-cloze#1]
Caught exception:
Traceback (most recent call last):
  File "aqt\progress.py", line 54, in handler
  File "aqt\main.py", line 150, in on_window_init
  File "aqt\main.py", line 198, in setupProfileAfterWebviewsLoaded
  File "aqt\main.py", line 245, in setupProfile
  File "aqt\main.py", line 425, in loadProfile
  File "aqt\hooks_gen.py", line 2913, in __call__
  File "anki\hooks.py", line 34, in runHook
  File "C:\Users\gusta\AppData\Roaming\Anki2\addons21\1990296174\enhanced_cloze.py", line 292, in addModel
    mw.col.models.add(enhancedModel)
  File "anki\models.py", line 204, in add
  File "anki\_backend\generated.py", line 438, in add_notetype_legacy
  File "anki\_backend\__init__.py", line 131, in _run_command
anki.errors.TemplateError: Card template ⁨1⁩ in notetype '⁨Enhanced Cloze 2.1⁩' has a problem.<br>Expected to find '{{cloze:Text}}' or similar on the front and back of the card template.

**Comment by RisingOrange** [comment]
Yes, but installation requires a workaround that is described on the AnkiWeb page of the add-on: https://ankiweb.net/shared/info/1990296174

**Comment by gustavosmendes** [comment]
> Yes, but installation requires a workaround that is described on the AnkiWeb page of the add-on: https://ankiweb.net/shared/info/1990296174

Hi, i did it. But there are new bugs in my Anki. It seems like they changed almost everything about Cloze_model. These code changes are giving me headaches.

**Comment by RisingOrange** [comment]
Yeah, the added various checks to ensure people are using clozes right and part of them are in the rust part of the code so it's harder to work around them when creating an add-on. The error above is a result of this.

Are you working on an add-on to convert basic notes to clozes?

**Comment by gustavosmendes** [comment]
not exactly. i am a med student, i dont know how to program properly. I tried tweaking(by brute force learning) your add-on for a while to version 2.1.45, but with no success. Thanks you!

**Comment by RisingOrange** [comment]
In the last update you don't need the workaround anymore. The name of the template the add-on uses is now "Enhanced Cloze 2.1 v2". Thought I would let you know.
