### ISSUE TITLE
An error occurred. 

### ISSUE THREAD

**Issue by noah579** [RisingOrange/anki-enhanced-cloze#13]
Debug info:
Anki 2.1.45 (355e66e8) Python 3.8.6 Qt 5.14.2 PyQt 5.14.2
Platform: Mac 10.16
Flags: frz=True ao=True sv=2
Add-ons, last update check: 2021-09-29 16:56:23
Add-ons possibly involved: ⁨Enhanced Cloze for Anki 21⁩

Caught exception:
Traceback (most recent call last):
  File "aqt/progress.py", line 54, in handler
  File "aqt/main.py", line 150, in on_window_init
  File "aqt/main.py", line 245, in setupProfile
  File "aqt/main.py", line 425, in loadProfile
  File "aqt/hooks_gen.py", line 2913, in __call__
  File "anki/hooks.py", line 34, in runHook
  File "/Users/noahnaf/Library/Application Support/Anki2/addons21/1990296174/modelFinder.py", line 14, in get_models
    _basic_note_type_ids = [mw.col.models.by_name(x)['id'] for x in ["Basic", tr.notetypes_basic_name()] if x]
  File "/Users/noahnaf/Library/Application Support/Anki2/addons21/1990296174/modelFinder.py", line 14, in <listcomp>
    _basic_note_type_ids = [mw.col.models.by_name(x)['id'] for x in ["Basic", tr.notetypes_basic_name()] if x]
TypeError: 'NoneType' object is not subscriptable

**Comment by RisingOrange** [comment]
Hi,
this error was caused by an incompatibility with the Automatic Basic to Cloze add-on. I uploaded an update for it. Please tell me if it works again after you update. You might need to go to Tools -> Addons and click "Check for updates" if the update does not appear by itself.

**Comment by noah579** [comment]
Hi,
Thank you so much for your fast response. It works again. :)

**Comment by RisingOrange** [comment]
:)

**Comment by youssef202020** [comment]
> :)

hi I have a problem
