### ISSUE TITLE
Hi,

### ISSUE THREAD

**Issue by youssef202020** [RisingOrange/anki-enhanced-cloze#20]
An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed.
If the issue only occurs when add-ons are enabled, please use the Tools > Add-ons menu item to disable some add-ons and restart Anki, repeating until you discover the add-on that is causing the problem.
When you've discovered the add-on that is causing the problem, please report the issue on the add-on support site.
Debug info:
Anki 2.1.49 (dc80804a) Python 3.8.6 Qt 5.14.2 PyQt 5.14.2
Platform: Windows 10
Flags: frz=True ao=True sv=2
Add-ons, last update check: 2022-01-15 06:52:50

Caught exception:
Traceback (most recent call last):
  File "aqt\progress.py", line 54, in handler
  File "aqt\main.py", line 149, in on_window_init
  File "aqt\main.py", line 197, in setupProfileAfterWebviewsLoaded
  File "aqt\main.py", line 244, in setupProfile
  File "aqt\main.py", line 403, in loadProfile
  File "decorator.py", line 232, in fun
  File "anki\hooks.py", line 89, in decorator_wrapper
  File "anki\hooks.py", line 80, in repl
  File "decorator.py", line 232, in fun
  File "anki\hooks.py", line 89, in decorator_wrapper
  File "anki\hooks.py", line 80, in repl
  File "decorator.py", line 232, in fun
  File "anki\hooks.py", line 89, in decorator_wrapper
  File "anki\hooks.py", line 81, in repl
  File "C:\Users\User\AppData\Roaming\Anki2\addons21\874215009\advancedbrowser\basic_fields.py", line 75, in myLoadCollection
    mw.col.db._db.create_function("nameForDeck", 1, self.nameForDeck)
AttributeError: 'DBProxy' object has no attribute '_db'

**Comment by youssef202020** [comment]
I can not open the app.

**Comment by RisingOrange** [comment]
Hello!
The error message says that the problem has something to do with the Advanced Browser add-on:
https://ankiweb.net/shared/info/874215009
You can try opening an issue there:
https://github.com/ankipalace/advanced-browser

Does the error only appear when you use the Advanced Browser add-on and the Enhanced Cloze add-on? Try disabling one or the other restart Anki and see if the error still shows up.
