### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'models'

### ISSUE THREAD

**Issue by GrimPixel** [RisingOrange/anki-enhanced-cloze#29]
Error
An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed.
If the issue only occurs when add-ons are enabled, please use the Tools > Add-ons menu item to disable some add-ons and restart Anki, repeating until you discover the add-on that is causing the problem.
When you've discovered the add-on that is causing the problem, please report the issue on the add-on support site.
Debug info:
Anki 2.1.50 (3564ece6) Python 3.10.2 Qt 5.15.2 PyQt 5.15.6
Platform: Linux
Flags: frz=False ao=True sv=?
Add-ons, last update check: 2022-03-18 03:16:06
Add-ons possibly involved: ⁨Enhanced Cloze for Anki 21⁩

Caught exception:
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/aqt/progress.py", line 115, in handler
    func()
  File "/usr/lib/python3.10/site-packages/aqt/main.py", line 188, in on_window_init
    gui_hooks.main_window_did_init()
  File "/usr/lib/python3.10/site-packages/aqt/hooks_gen.py", line 2696, in __call__
    hook()
  File "/home/grim/.local/share/Anki2/addons21/1990296174/enhanced_cloze.py", line 94, in on_profile_did_open
    add_compatibilty_aliases()
  File "/home/grim/.local/share/Anki2/addons21/1990296174/compat.py", line 11, in add_compatibilty_aliases
    add_compatibility_alias(aqt.mw.col.models, "by_name", "byName")
AttributeError: 'NoneType' object has no attribute 'models'

**Comment by LKirst** [comment]
I get the same error message for `add_compatibilty_aliases`  on Windows 10 (Anki 2.1.49 (dc80804a) Python 3.8.6 Qt 5.14.2 PyQt 5.14.2; Flags: frz=True ao=True sv=?)
